<!-- shell chrome icons + the icon-catalog names used across the apps built so far -->
<script lang="ts">
	import {
		faHouse,
		faWifi,
		faSignal,
		faFlagCheckered,
		faPeopleGroup,
		faGear,
		faBusinessTime,
		faUserSecret,
		faSpider,
		faFolderOpen,
		faXmark,
		faMinus,
		faArrowsRotate,
		faChevronLeft,
		faChevronRight,
		faImage,
		faSwatchbook,
		faBell,
		faBellSlash,
		faVolumeHigh,
		faVolumeXmark,
		faCircleExclamation,
		faCheck,
		faTriangleExclamation,
		faCircleInfo,
		faCircleCheck,
		faFileLines,
		faMoneyCheckDollar,
		faCar,
		faPlus,
		faUsers,
		faBullhorn,
		faLocationCrosshairs,
		faMagnifyingGlass,
		faSave,
		faHammer,
		faCopy,
		faThumbtack,
		faTrash,
		faPen,
		faFileContract,
		faScrewdriverWrench,
		faCartShopping,
		faClockRotateLeft,
		type IconDefinition,
	} from '@fortawesome/free-solid-svg-icons';

	const ICONS: Record<string, IconDefinition> = {
		house: faHouse,
		wifi: faWifi,
		signal: faSignal,
		'flag-checkered': faFlagCheckered,
		'people-group': faPeopleGroup,
		gear: faGear,
		'business-time': faBusinessTime,
		'user-secret': faUserSecret,
		'spider-web': faSpider,
		'folder-open': faFolderOpen,
		xmark: faXmark,
		minus: faMinus,
		'arrows-rotate': faArrowsRotate,
		'chevron-left': faChevronLeft,
		'chevron-right': faChevronRight,
		image: faImage,
		swatchbook: faSwatchbook,
		bell: faBell,
		'bell-slash': faBellSlash,
		'volume-high': faVolumeHigh,
		'volume-xmark': faVolumeXmark,
		'circle-exclamation': faCircleExclamation,
		check: faCheck,
		'triangle-exclamation': faTriangleExclamation,
		'circle-info': faCircleInfo,
		'circle-check': faCircleCheck,
		'file-lines': faFileLines,
		'money-check-dollar': faMoneyCheckDollar,
		car: faCar,
		cars: faCar,
		plus: faPlus,
		users: faUsers,
		'face-awesome': faBullhorn,
		bullhorn: faBullhorn,
		'location-crosshairs': faLocationCrosshairs,
		'magnifying-glass': faMagnifyingGlass,
		save: faSave,
		'steering-wheel': faCar,
		hammer: faHammer,
		copy: faCopy,
		thumbtack: faThumbtack,
		trash: faTrash,
		pen: faPen,
		'file-contract': faFileContract,
		'screwdriver-wrench': faScrewdriverWrench,
		'cart-shopping': faCartShopping,
		'clock-rotate-left': faClockRotateLeft,
	};

	let { name, size = '1em' }: { name: string; size?: string } = $props();

	const icon = $derived(ICONS[name] ?? faCircleExclamation);
	const path = $derived(icon.icon[4] as string);
	const viewBox = $derived(`0 0 ${icon.icon[0]} ${icon.icon[1]}`);
</script>

<svg {viewBox} width={size} height={size} fill="currentColor" aria-hidden="true">
	<path d={path} />
</svg>
