return {
	lsu = {
		boosting = {
			-- exterior encounter ped models
			pedModels = {
				`a_m_m_afriamer_01`,
				`a_m_m_fatlatin_01`,
				`a_m_m_business_01`,
				`a_m_m_golfer_01`,
				`a_m_m_indian_01`,
				`a_m_m_mexlabor_01`,
				`a_m_m_prolhost_01`,
				`a_m_m_soucent_01`,
				`a_m_m_stlat_02`,
				`a_m_m_tourist_01`,
				`a_m_o_salton_01`,
				`a_m_y_beachvesp_01`,
				`a_m_y_bevhills_02`,
				`a_m_y_busicas_01`,
				`a_m_y_business_01`,
				`a_m_y_business_02`,
				`a_m_y_business_03`,
				`s_m_m_autoshop_02`,
				`s_m_m_autoshop_01`,
				`s_m_m_cntrybar_01`,
				`s_m_m_ccrew_01`,
				`s_m_m_gentransport`,
				`s_m_m_movspace_01`,
				`s_f_m_sweatshop_01`,
				`s_f_m_shop_high`,
				`A_F_M_EastSA_01`,
				`A_F_M_EastSA_02`,
				`A_F_M_Downtown_01`,
				`A_F_M_Business_02`,
				`A_F_M_BevHills_02`,
				`A_F_M_FatWhite_01`,
				`A_F_M_Salton_01`,
				`A_F_O_GenStreet_01`,
				`A_F_Y_BevHills_01`,
				`A_F_Y_BevHills_03`,
				`a_f_y_epsilon_01`,
				`a_f_y_eastsa_03`,
				`a_f_y_eastsa_01`,
				`a_f_y_hiker_01`,
			},

			-- weapon loot per vehicle class
			weaponsForClass = {
				D = {
					{5, `WEAPON_BAT`},
					{5, `WEAPON_GOLFCLUB`},
					{5, `WEAPON_MACHETE`},
					{70, `WEAPON_UNARMED`},
					{5, `WEAPON_KNIFE`},
					{5, `WEAPON_WRENCH`},
					{5, `WEAPON_HAMMER`},
					{5, `WEAPON_POOLCUE`},
					{5, `WEAPON_BOTTLE`},
				},
				C = {
					{5, `WEAPON_BAT`},
					{5, `WEAPON_GOLFCLUB`},
					{5, `WEAPON_MACHETE`},
					{50, `WEAPON_UNARMED`},
					{5, `WEAPON_KNIFE`},
					{5, `WEAPON_WRENCH`},
					{5, `WEAPON_HAMMER`},
					{1, `WEAPON_PISTOL`},
					{5, `WEAPON_POOLCUE`},
					{5, `WEAPON_BOTTLE`},
				},
				B = {
					{5, `WEAPON_BAT`},
					{2, `WEAPON_MACHETE`},
					{40, `WEAPON_UNARMED`},
					{5, `WEAPON_KNIFE`},
					{5, `WEAPON_WRENCH`},
					{5, `WEAPON_HAMMER`},
					{5, `WEAPON_BOTTLE`},
					{5, `WEAPON_PISTOL`},
					{2, `WEAPON_SNSPISTOL`},
					{5, `WEAPON_REVOLVER`},
					{2, `WEAPON_PISTOL50`},
					{1, `WEAPON_APPISTOL`},
				},
				A = {
					{5, `WEAPON_BAT`},
					{8, `WEAPON_MACHETE`},
					{20, `WEAPON_UNARMED`},
					{8, `WEAPON_KNIFE`},
					{8, `WEAPON_WRENCH`},
					{5, `WEAPON_PISTOL`},
					{5, `WEAPON_SNSPISTOL`},
					{5, `WEAPON_REVOLVER`},
					{5, `WEAPON_PISTOL50`},
					{1, `WEAPON_PUMPSHOTGUN`},
					{5, `WEAPON_APPISTOL`},
				},
				["A+"] = {
					{5, `WEAPON_MACHETE`},
					{1, `WEAPON_UNARMED`},
					{5, `WEAPON_KNIFE`},
					{5, `WEAPON_SNSPISTOL`},
					{5, `WEAPON_REVOLVER`},
					{5, `WEAPON_PISTOL50`},
					{5, `WEAPON_PUMPSHOTGUN`},
					{5, `WEAPON_APPISTOL`},
					{2, `WEAPON_SAWNOFFSHOTGUN`},
					{1, `WEAPON_MICROSMG`},
					{1, `WEAPON_MINISMG`},
				},
				["S+"] = {
					{1, `WEAPON_MACHETE`},
					{2, `WEAPON_REVOLVER`},
					{5, `WEAPON_PISTOL50`},
					{5, `WEAPON_PUMPSHOTGUN`},
					{5, `WEAPON_APPISTOL`},
					{5, `WEAPON_SAWNOFFSHOTGUN`},
					{5, `WEAPON_MICROSMG`},
					{5, `WEAPON_MINISMG`},
					{4, `WEAPON_ASSAULTRIFLE`},
					{4, `WEAPON_COMBATPDW`},
				},
			},

			-- tracker-hack minigame difficulty per vehicle class
			trackerHacks = {
				["S+"] = {
					rows = 10,
					lengthMin = 4,
					lengthMax = 6,
					duration = 20000,
					charSize = 2,
					charSet = {
						{15, "alphanumer"},
						{10, "symbols"},
						{15, "greek"},
						{10, "currency"},
						{5, "braille"},
					}
				},
				["A+"] = {
					rows = 10,
					lengthMin = 4,
					lengthMax = 6,
					duration = 20000,
					charSize = 2,
					charSet = {
						{20, "alphanumer"},
						{5, "symbols"},
						{10, "greek"},
						{2, "currency"},
					}
				},
				A = {
					rows = 8,
					lengthMin = 3,
					lengthMax = 5,
					duration = 25000,
					charSize = 2,
					charSet = {
						{25, "alphanumer"},
						{15, "alphabet"},
						{2, "symbols"},
						{10, "greek"},
					}
				},
				B = {
					rows = 8,
					lengthMin = 2,
					lengthMax = 4,
					duration = 25000,
					charSize = 1,
					charSet = {
						{5, "numeric"},
						{20, "alphabet"},
						{15, "alphanumer"},
						{1, "greek"},
					}
				},
			},
		},

		chopping = {
			-- choppable vehicle bone list (wheels/doors) with distance + strip duration
			vehBones = {
				{ name = "wheel_lf", distance = 1.6, index = 0, type = "tire", duration = 3000 },
				{ name = "wheel_rf", distance = 1.6, index = 1, type = "tire", duration = 3000 },
				{ name = "wheel_lm", distance = 1.6, index = 2, type = "tire", duration = 3000 },
				{ name = "wheel_rm", distance = 1.6, index = 3, type = "tire", duration = 3000 },
				{ name = "wheel_lr", distance = 1.6, index = 4, type = "tire", duration = 3000 },
				{ name = "wheel_rr", distance = 1.6, index = 5, type = "tire", duration = 3000 },
				{ name = "wheel_lm1", distance = 1.6, index = 2, type = "tire", duration = 3000 },
				{ name = "wheel_rm1", distance = 1.6, index = 3, type = "tire", duration = 3000 },
				{ name = "door_dside_f", distance = 1.8, index = 0, type = "door", duration = 6000 },
				{ name = "door_pside_f", distance = 1.8, index = 1, type = "door", duration = 6000 },
				{ name = "door_dside_r", distance = 1.8, index = 2, type = "door", duration = 6000 },
				{ name = "door_pside_r", distance = 1.8, index = 3, type = "door", duration = 6000 },
				{ name = "bonnet", distance = 2.8, index = 4, type = "door", duration = 9000 },
				{ name = "boot", distance = 1.6, index = 5, type = "door", duration = 9000 },
			},
		},
	},
}
